module.exports = {
  "container":{
    flex:1,
    justifyContent:'center',
    backgroundColor:'#4a90e2',
    padding:0,
  },
  "manstyle":{
    flex:1,
    width: 90,
    height: 90,
    resizeMode: 'contain',
  },
  "buttonImagestyle":{
    width:30,
    height:17,
  },
  "buttonupstyle":{
    width:30,
    height:17,
  },
  "buttondownstyle":{
    width:30,
    height:17,
  },
  "scrollView": {
    margin: 10,
    paddingBottom: 20,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  "track": {
    height: 18,
    borderRadius: 1,
    backgroundColor: '#ff0000',
  },
  "thumb": {
    width: 20,
    height: 30,
    borderRadius: 1,
    backgroundColor: '#838486',
  },
  "headerView":{
    flex:1,
    backgroundColor:'transparent',
    alignItems:'center',
  },
  "bodyView":{
    flex:9,
    backgroundColor:'#ffffff',
  },
  "headText":{textAlign:'center',marginTop:24,fontSize:28,color:'#ffffff'},
  "imagestyle":{marginTop:95,marginLeft:0,resizeMode: 'contain',},
  "imageView":{flex:4,backgroundColor:'transparent',alignItems:'center',},
  "textView":{flex:2,backgroundColor:'transparent',},
  "buttonView":{flex:3,backgroundColor:'transparent',flexDirection:'row',paddingTop:80,},
  "firstButton":{paddingTop:10,
    height:50,
    overflow:'hidden',
    borderBottomLeftRadius:0,
    borderTopLeftRadius:0,
    borderTopRightRadius:0,
    borderBottomRightRadius:0,
    backgroundColor: '#ffffff',
    borderWidth:2,
    borderColor:'#000000'
  },
  "secondButton":{
    paddingTop:10,
    height:50,
    overflow:'hidden',
    backgroundColor: '#4a90e2',
    borderWidth:2,
    borderColor:'#000000'
  },
  "thirdButton":{
    paddingTop:10,
    height:50,
    borderBottomRightRadius:0,
    borderTopRightRadius:0,
    overflow:'hidden',
    backgroundColor: '#ffffff',
    borderWidth:2,
    borderColor:'#000000'
  },
  "save":{
    paddingTop:10,
    marginTop:40,
    height:50,
    width:150,
    marginLeft:20,
    borderRadius:30,
    overflow:'hidden',
    backgroundColor: '#ffffff',
    borderWidth:1,
    borderColor:'#000000'
  },
  "cancel":{
    paddingTop:10,
    marginTop:40,
    height:50,
    width:150,
    marginLeft:30,
    borderRadius:30,
    overflow:'hidden',
    backgroundColor: '#ffffff',
    borderWidth:1,
    borderColor:'#000000'
  },
  }
